export enum TodoReducerActionTypes {
   Add_TODO_TO_CURRENT_TASK = 'Add_TODO_TO_CURRENT_TASK',
   Add_TODO_TO_TODO_LIST = 'Add_TODO_TO_TODO_LIST',
   Update_TODO = 'Update_TODO',
   UPDATE_CURR_TASK_TOMATO_COUNT_PLUS_1 = 'UPDATE_CURR_TASK_TOMATO_COUNT_PLUS_1',
} 